service: sls-layers-python

provider:
  name: aws
  runtime: python3.6

package:
  exclude:
    - venv/**
    - node_modules/**

custom:
  pythonRequirements:
    dockerizePip: non-linux
    noDeploy:
      - numpy

functions:
  hello:
    handler: handler.hello
    layers:
      - arn:aws:lambda:us-east-1:XXXXXXXXX:layer:numpy:1

plugins:
  - serverless-python-requirements
